version: '3.8'
services:
    queue:
        build: ./msg_queue
        hostname: queue
        restart: always
        depends_on:
            - rabbitmq
        ports:
            - 8111:8111
    client:
        build: ./client
        hostname: client
        restart: always
        depends_on:
            - api

    # postgres:
    #     hostname: postgres
    #     image: postgres:14.1-alpine
    #     restart: always
    #     volumes:
    #         - ./postgresql:/var/lib/postgresql
    #     environment:
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=root
    #         - POSTGRES_DB=ds-a1

    #         # - POSTGRES_HOST_AUTH_METHOD=trust
    #     ports:
    #         - 5432:5432

    api:
        build: ./server
        hostname: api
        restart: always
        environment:
            - NODE_ENV=production
        ports:
            - 8000:8000

    nginx:
        depends_on:
            - client
            - api
        restart: always
        build: ./nginx
        ports:
            - 80:80

    rabbitmq:
        image: rabbitmq:3.11-management
        hostname: rabbitmq
        restart: always
        ports:
            - 5672:5672

    chat_server:
        container_name: chat_server
        restart: on-failure
        build: ./chat_server
        volumes:
            - ./chat_server:/app/chat_server
        ports:
            - '8080:8080'
